[package]
name = "agent"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
futures-util = { workspace = true }
proto = { path = "../proto" }
quinn = { workspace = true }
reqwest = { workspace = true }
rustls = { workspace = true }
rustls-pemfile = { workspace = true }
serde = { workspace = true }
serde_yaml_ng = "0.10"
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
rcgen = { workspace = true }
tempfile = "3"

[lints]
workspace = true
